### ISSUE TITLE
File size is much larger than it could be

### ISSUE THREAD

**Issue by lewisclement** [nick92/tranqil#37]
The music is distributed uncompressed, which makes the app installer 178 MB (!) large as of version 1.1.  Almost undownloadable at my current location, and on bad connections in general. I suggest using Opus or Vorbis codecs.

**Comment by nick92** [comment]
Thanks for your suggestion

This issue has now been resolved in release [1.1.6](https://github.com/nick92/tranqil/releases/tag/1.1.6)
